server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: root

custom:
  message: "Patient Service Config Loaded from Config Server"